version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: master
  assignees:
  - acdibble
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: chai
    versions:
    - 4.3.3
  - dependency-name: nock
    versions:
    - 13.0.10
    - 13.0.6
    - 13.0.7
    - 13.0.8
    - 13.0.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
    - 14.14.31
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  rebase-strategy: disabled
